import { Button, Input, Loader, useKumoToastManager } from "@cloudflare/kumo";
import { AddressBookIcon, EnvelopeSimpleIcon, PencilSimpleIcon, PlusIcon, TrashIcon } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router";
import { useMailbox, useUpdateMailbox } from "~/queries/mailboxes";
import api from "~/services/api";
import type { Email } from "~/types";

interface Contact { id:string; name:string; email:string; company?:string; position?:string; phone?:string; notes?:string; }
function normalizeContact(c:Partial<Contact>):Contact{const email=(c.email||"").trim().toLowerCase();return{id:c.id||email,name:(c.name||email.split("@")[0]||"Contact").trim(),email,company:c.company?.trim()||"",position:c.position?.trim()||"",phone:c.phone?.trim()||"",notes:c.notes?.trim()||""};}
function asEmails(value:Email[]|{emails:Email[]}|undefined){return Array.isArray(value)?value:(value?.emails||[]);}

export default function ContactsRoute(){
 const{mailboxId}=useParams<{mailboxId:string}>();const navigate=useNavigate();const toast=useKumoToastManager();const{data:mailbox,isLoading}=useMailbox(mailboxId);const updateMailbox=useUpdateMailbox();
 const[contacts,setContacts]=useState<Contact[]>([]);const[query,setQuery]=useState("");const[editing,setEditing]=useState<Contact|null>(null);const[showForm,setShowForm]=useState(false);const[selected,setSelected]=useState<Contact|null>(null);const[contactEmails,setContactEmails]=useState<Email[]>([]);const[loadingEmails,setLoadingEmails]=useState(false);
 useEffect(()=>{const stored=mailbox?.settings?.contacts;setContacts(Array.isArray(stored)?stored.map(normalizeContact).filter(c=>c.email):[]);},[mailbox]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?contacts.filter(c=>[c.name,c.email,c.company,c.position,c.phone].some(v=>(v||"").toLowerCase().includes(q))):contacts;},[contacts,query]);
 const saveContacts=async(next:Contact[])=>{if(!mailboxId||!mailbox)return;try{await updateMailbox.mutateAsync({mailboxId,settings:{...mailbox.settings,contacts:next}});setContacts(next);}catch{toast.add({title:"Failed to save contact",variant:"error"});throw new Error("save contact failed");}};
 const openContact=async(c:Contact)=>{setSelected(c);setLoadingEmails(true);try{const[a,b]=await Promise.all([api.searchEmails(mailboxId!,{from:c.email,limit:"100"}),api.searchEmails(mailboxId!,{to:c.email,limit:"100"})]);const merged=new Map<string,Email>();[...asEmails(a),...asEmails(b)].forEach(e=>merged.set(e.id,e));setContactEmails(Array.from(merged.values()).sort((x,y)=>new Date(y.date).getTime()-new Date(x.date).getTime()));}catch{toast.add({title:"Failed to load contact emails",variant:"error"});setContactEmails([]);}finally{setLoadingEmails(false);}};
 const deleteContact=async(c:Contact)=>{try{await saveContacts(contacts.filter(x=>x.id!==c.id));if(selected?.id===c.id)setSelected(null);}catch{}};
 if(isLoading||!mailbox)return <div className="flex justify-center py-20"><Loader size="lg"/></div>;
 return <div className="h-full overflow-y-auto p-4 md:p-8"><div className="max-w-5xl mx-auto"><div className="flex items-center justify-between gap-4 mb-6"><div><div className="flex items-center gap-2"><AddressBookIcon size={21}/><h1 className="text-xl font-semibold">Contacts</h1></div><p className="text-sm text-kumo-subtle mt-1">Manage contacts and view every email exchanged with them.</p></div><Button variant="primary" icon={<PlusIcon size={16}/>} onClick={()=>{setEditing({id:crypto.randomUUID(),name:"",email:"",company:"",position:"",phone:"",notes:""});setShowForm(true);}}>Add Contact</Button></div>
 <Input label="Search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, company..."/>
 <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)] gap-5 mt-5"><div className="rounded-lg border border-kumo-line bg-kumo-base divide-y divide-kumo-line overflow-hidden">{filtered.length===0?<div className="p-8 text-center text-sm text-kumo-subtle">No contacts yet.</div>:filtered.map(c=><button key={c.id} type="button" onClick={()=>void openContact(c)} className={`w-full text-left px-4 py-3 hover:bg-kumo-tint ${selected?.id===c.id?"bg-kumo-fill":""}`}><div className="flex items-center justify-between gap-2"><div className="font-medium truncate">{c.name}</div><div className="flex gap-1 shrink-0"><span onClick={e=>{e.stopPropagation();setEditing(c);setShowForm(true)}} className="p-1.5 rounded hover:bg-kumo-tint"><PencilSimpleIcon size={15}/></span><span onClick={e=>{e.stopPropagation();void deleteContact(c)}} className="p-1.5 rounded hover:bg-kumo-tint"><TrashIcon size={15}/></span></div></div><div className="text-sm text-kumo-subtle truncate">{c.email}</div><div className="text-xs text-kumo-subtle mt-1 truncate">{[c.company,c.position].filter(Boolean).join(" · ")}</div></button>)}</div>
 <div className="rounded-lg border border-kumo-line bg-kumo-base min-h-[300px]">{!selected?<div className="h-full min-h-[300px] flex items-center justify-center text-sm text-kumo-subtle">Select a contact to see all emails.</div>:<><div className="p-5 border-b border-kumo-line"><div className="text-lg font-semibold">{selected.name}</div><div className="text-sm text-kumo-subtle">{selected.email}</div><div className="flex gap-2 mt-3"><Button size="sm" variant="secondary" icon={<EnvelopeSimpleIcon size={14}/>} onClick={()=>navigate(`/mailbox/${mailboxId}`)}>New Email</Button></div></div>{loadingEmails?<div className="flex justify-center py-10"><Loader/></div>:contactEmails.length===0?<div className="p-8 text-center text-sm text-kumo-subtle">No emails found.</div>:<div className="divide-y divide-kumo-line">{contactEmails.map(e=><button key={e.id} type="button" onClick={()=>navigate(`/mailbox/${mailboxId}/emails/${e.folder_id||"inbox"}?email=${encodeURIComponent(e.id)}`)} className="w-full text-left p-4 hover:bg-kumo-tint"><div className="flex justify-between gap-3"><span className="font-medium truncate">{e.subject||"(No subject)"}</span><span className="text-xs text-kumo-subtle shrink-0">{new Date(e.date).toLocaleString()}</span></div><div className="text-xs text-kumo-subtle mt-1 truncate">{e.sender} → {e.recipient}</div></button>)}</div>}</>}</div></div></div>
 {showForm&&editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-xl border border-kumo-line bg-kumo-base shadow-xl p-6"><h2 className="text-lg font-semibold mb-5">{contacts.some(c=>c.id===editing.id)?"Edit Contact":"Add Contact"}</h2><ContactForm contact={editing} onCancel={()=>setShowForm(false)} onSave={async c=>{const next=contacts.some(x=>x.id===c.id)?contacts.map(x=>x.id===c.id?c:x):[...contacts,c];await saveContacts(next);setShowForm(false);}}/></div></div>}</div>;
}
function ContactForm({contact,onCancel,onSave}:{contact:Contact;onCancel:()=>void;onSave:(contact:Contact)=>Promise<void>}){const[form,setForm]=useState(contact);const set=(k:keyof Contact)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm(v=>({...v,[k]:e.target.value}));return <form className="space-y-3" onSubmit={e=>{e.preventDefault();if(form.email.trim())void onSave(normalizeContact(form));}}><Input label="Name" value={form.name} onChange={set("name")} required/><Input label="Email" type="email" value={form.email} onChange={set("email")} required/><Input label="Company" value={form.company||""} onChange={set("company")}/><Input label="Position" value={form.position||""} onChange={set("position")}/><Input label="Phone" value={form.phone||""} onChange={set("phone")}/><textarea className="w-full rounded-md border border-kumo-line bg-kumo-base px-3 py-2 text-sm" rows={3} placeholder="Notes" value={form.notes||""} onChange={set("notes")}/><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" variant="primary">Save</Button></div></form>;}
